# .cirrus.yml
container:
  image: ubuntu:22.04
  cpu: 8
  memory: 24G

env:
  GITHUB_TOKEN: ENCRYPTED[!4b0eae3c2c6c631068eeedfaa0d2c0aa44b3c52d2e3d50dc4f5fb71f958d334548e3f4d70eeb23292bfb454df755b503!]
  CIRRUS_API_TOKEN: ENCRYPTED[!4336ebf698c76189e6057b84bf85a3809af77f5e5db08cf99abeea89c96a5ef9b34480dad12847b35388578fef3ba6ed!]
  DEBIAN_FRONTEND: noninteractive

task:
  name: Minecraft Fabric + Velocity
  timeout_in: 120m

  install_java_script:
    - apt-get update -qq
    - apt-get install -y openjdk-21-jre-headless git curl jq > /dev/null 2>&1
    
  run_server_script:
    - |
      echo "Starting Fabric Server on port 25565..."
      java -Xmx21G -Xms17G \
        -XX:+UseG1GC \
        -XX:+ParallelRefProcEnabled \
        -XX:MaxGCPauseMillis=200 \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+DisableExplicitGC \
        -XX:+AlwaysPreTouch \
        -XX:G1NewSizePercent=30 \
        -XX:G1MaxNewSizePercent=40 \
        -XX:G1HeapRegionSize=16M \
        -XX:G1ReservePercent=20 \
        -XX:G1HeapWastePercent=5 \
        -XX:G1MixedGCCountTarget=4 \
        -XX:InitiatingHeapOccupancyPercent=15 \
        -XX:G1MixedGCLiveThresholdPercent=90 \
        -XX:G1RSetUpdatingPauseTimePercent=5 \
        -XX:SurvivorRatio=32 \
        -XX:+PerfDisableSharedMem \
        -XX:MaxTenuringThreshold=1 \
        -jar fabric-server.jar nogui 2>&1 | tee server.log &
      SERVER_PID=$!
      
      echo "Fabric Server started (PID: $SERVER_PID)"
      sleep 10
      
      echo "Starting Velocity Proxy on port 25577..."
      cd velocity
      java -Xmx1G -Xms512M \
        -XX:+UseG1GC \
        -XX:G1HeapRegionSize=4M \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+ParallelRefProcEnabled \
        -XX:+DisableExplicitGC \
        -XX:+AlwaysPreTouch \
        -jar velocity.jar 2>&1 | tee velocity.log &
      VELOCITY_PID=$!
      cd ..
      
      echo "Velocity started (PID: $VELOCITY_PID)"
      sleep 5
      
      echo "Starting Playit tunnel..."
      chmod +x playit-linux-amd64
      
      (while true; do
        ./playit-linux-amd64 2>&1 | tee -a playit.log
        sleep 5
      done) &
      
      echo ""
      echo "=== ALL SERVICES RUNNING ==="
      echo "Fabric: 21GB RAM on port 25565"
      echo "Velocity: 1GB RAM on port 25577"
      echo "Playit: Check logs for connection address"
      echo ""
      
      MAX_TIME=900
      ELAPSED=0
      
      while [ $ELAPSED -lt $MAX_TIME ]; do
        if ! kill -0 $SERVER_PID 2>/dev/null; then
          echo "Fabric server stopped"
          break
        fi
        if ! kill -0 $VELOCITY_PID 2>/dev/null; then
          echo "Velocity stopped, restarting..."
          cd velocity
          java -Xmx1G -Xms512M -XX:+UseG1GC -jar velocity.jar 2>&1 | tee -a velocity.log &
          VELOCITY_PID=$!
          cd ..
        fi
        sleep 10
        ELAPSED=$((ELAPSED + 10))
        
        if [ $((ELAPSED % 600)) -eq 0 ]; then
          echo "=== Running for $((ELAPSED / 60)) minutes ==="
        fi
      done
      
      echo "Shutting down all services..."
      kill -TERM $SERVER_PID $VELOCITY_PID 2>/dev/null || true
      pkill -TERM playit-linux-amd64 2>/dev/null || true
      sleep 10
      
      echo "=== Final Logs ==="
      echo "Fabric (last 30 lines):"
      tail -30 server.log
      echo ""
      echo "Velocity (last 20 lines):"
      tail -20 velocity/velocity.log

  always:
    save_world_script:
      - git config user.email "bot@cirrus-ci.com"
      - git config user.name "Cirrus Bot"
      - git add -A
      - git diff --cached --quiet || git commit -m "Auto-save $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
      - git push https://x-access-token:${GITHUB_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git HEAD:main || true
    
    retrigger_script:
      - sleep 60
      - |
        REPO_ID=$(curl -s \
          -H "Authorization: Bearer ${CIRRUS_API_TOKEN}" \
          -H "Content-Type: application/json" \
          -d '{"query":"query { githubRepository(owner: \"'$(echo ${CIRRUS_REPO_FULL_NAME} | cut -d/ -f1)'\", name: \"'$(echo ${CIRRUS_REPO_FULL_NAME} | cut -d/ -f2)'\") { id } }"}' \
          https://api.cirrus-ci.com/graphql | jq -r '.data.githubRepository.id')
        
        if [ -n "$REPO_ID" ] && [ "$REPO_ID" != "null" ]; then
          curl -X POST \
            -H "Authorization: Bearer ${CIRRUS_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{"query":"mutation { trigger(input: {repositoryId: \"'$REPO_ID'\", branch: \"main\"}) { build { id } } }"}' \
            https://api.cirrus-ci.com/graphql
        fi
