# .cirrus.yml
container:
  image: ghcr.io/graalvm/jdk-community:21
  cpu: 8
  memory: 24G

env:
  GITHUB_TOKEN: ENCRYPTED[!4b0eae3c2c6c631068eeedfaa0d2c0aa44b3c52d2e3d50dc4f5fb71f958d334548e3f4d70eeb23292bfb454df755b503!]
  CIRRUS_API_TOKEN: ENCRYPTED[!4336ebf698c76189e6057b84bf85a3809af77f5e5db08cf99abeea89c96a5ef9b34480dad12847b35388578fef3ba6ed!]

task:
  name: Minecraft Fabric Server 1.20.1
  timeout_in: 120m

  setup_script:
    - apt-get update -qq && apt-get install -y git > /dev/null 2>&1
    - chmod +x playit-linux-amd64 || true

  run_server_script:
    - |
      echo "=== Starting Minecraft server ==="
      java -Xmx20G -Xms16G \
        -XX:+UseG1GC \
        -XX:+ParallelRefProcEnabled \
        -XX:MaxGCPauseMillis=200 \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+DisableExplicitGC \
        -XX:+AlwaysPreTouch \
        -XX:G1NewSizePercent=30 \
        -XX:G1MaxNewSizePercent=40 \
        -XX:G1HeapRegionSize=16M \
        -XX:G1ReservePercent=20 \
        -XX:G1HeapWastePercent=5 \
        -XX:G1MixedGCCountTarget=4 \
        -XX:InitiatingHeapOccupancyPercent=15 \
        -XX:G1MixedGCLiveThresholdPercent=90 \
        -XX:G1RSetUpdatingPauseTimePercent=5 \
        -XX:SurvivorRatio=32 \
        -XX:+PerfDisableSharedMem \
        -XX:MaxTenuringThreshold=1 \
        -jar fabric-server.jar nogui > server.log 2>&1 &
      SERVER_PID=$!

      # استنى لحد ما يبدأ السيرفر فعلاً
      echo "=== Waiting for server to start ==="
      for i in {1..60}; do
        if grep -q "Done (" server.log 2>/dev/null; then
          echo "Server started successfully!"
          break
        fi
        sleep 5
      done

      # بعد ما السيرفر يشتغل فعلاً — نشغل playit
      echo "=== Starting Playit Tunnel ==="
      (while true; do
        ./playit-linux-amd64 >> playit.log 2>&1
        echo "[Playit] Restarting after crash..."
        sleep 5
      done) &
      PLAYIT_PID=$!

      echo "=== Monitoring processes every 10 minutes ==="
      COUNTER=0
      while kill -0 $SERVER_PID 2>/dev/null; do
        sleep 600  # كل 10 دقايق
        COUNTER=$((COUNTER + 1))
        echo "[Monitor] Check #$COUNTER — $(date '+%H:%M:%S')"

        # تأكيد أن السيرفر لسه شغال
        if ! kill -0 $SERVER_PID 2>/dev/null; then
          echo "[Monitor] Server stopped! Exiting loop..."
          break
        fi

        # تأكيد أن playit لسه شغال
        if ! kill -0 $PLAYIT_PID 2>/dev/null; then
          echo "[Monitor] Playit stopped! Restarting..."
          (./playit-linux-amd64 >> playit.log 2>&1 &)
          PLAYIT_PID=$!
        fi

        # طباعة آخر سطرين من لوج السيرفر كل 10 دقايق
        echo "=== Last server log lines ==="
        tail -n 5 server.log || true
      done

      echo "=== Stopping all processes ==="
      kill -TERM $SERVER_PID 2>/dev/null || true
      pkill -TERM playit-linux-amd64 2>/dev/null || true
      sleep 5

  save_everything_script:
    - git config user.email "bot@cirrus-ci.com"
    - git config user.name "Cirrus Bot"
    - git add -A
    - git diff --cached --quiet || git commit -m "Auto-save $(date -u '+%Y-%m-%d %H:%M:%S')"
    - git push https://x-access-token:${GITHUB_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git HEAD:main || true

  always:
    retrigger_script:
      - sleep 30
      - git fetch origin
      - git reset --hard origin/main
      - |
        curl -X POST \
          -H "Authorization: Bearer ${CIRRUS_API_TOKEN}" \
          -H "Content-Type: application/json" \
          "https://api.cirrus-ci.com/graphql" \
          -d '{"query":"mutation { trigger(input: {repositoryId: \"'${CIRRUS_REPO_ID}'\", branch: \"main\"}) { build { id } } }"}'
          
