# .cirrus.yml
container:
  image: eclipse-temurin:21-jdk
  cpu: 8
  memory: 24G

task:
  name: Minecraft Fabric Server 1.20.1
  timeout_in: 120m
  
  setup_playit_script:
    - chmod +x playit-linux-amd64
    - |
      if [ -n "$CIRRUS_ENCRYPTED_PLAYIT_SECRET" ]; then
        echo "$CIRRUS_ENCRYPTED_PLAYIT_SECRET" > playit.toml
      fi
    - ./playit-linux-amd64 >/dev/null 2>&1 &
    - sleep 10
  
  run_server_script:
    - |
      java -Xmx22G -Xms18G \
        -XX:+UseG1GC \
        -XX:+ParallelRefProcEnabled \
        -XX:MaxGCPauseMillis=200 \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+DisableExplicitGC \
        -XX:+AlwaysPreTouch \
        -XX:G1NewSizePercent=30 \
        -XX:G1MaxNewSizePercent=40 \
        -XX:G1HeapRegionSize=16M \
        -XX:G1ReservePercent=20 \
        -XX:G1HeapWastePercent=5 \
        -XX:G1MixedGCCountTarget=4 \
        -XX:InitiatingHeapOccupancyPercent=15 \
        -XX:G1MixedGCLiveThresholdPercent=90 \
        -XX:G1RSetUpdatingPauseTimePercent=5 \
        -XX:SurvivorRatio=32 \
        -XX:+PerfDisableSharedMem \
        -XX:MaxTenuringThreshold=1 \
        -jar fabric-server.jar nogui &
      SERVER_PID=$!
      
      while kill -0 $SERVER_PID 2>/dev/null; do
        sleep 10
      done
  
  save_world_script:
    - git config user.email "cirrus@ci.com"
    - git config user.name "Cirrus CI"
    - git add -A
    - git diff --cached --quiet || git commit -m "Auto-save $(date)"
    - git push origin main
  
  always:
    retrigger_script:
      - |
        if [ "$CIRRUS_BRANCH" = "main" ]; then
          curl -X POST \
            -H "Authorization: Bearer $CIRRUS_ENCRYPTED_API_TOKEN" \
            "https://api.cirrus-ci.com/github/$CIRRUS_REPO_FULL_NAME/re-run?taskId=$CIRRUS_TASK_ID"
        fi
